### ISSUE TITLE
Merged / Deleted Contacts Appear in Membership Pivot Report

### ISSUE THREAD

**Issue by amyers735** [eileenmcnaughton/nz.co.fuzion.extendedreport#295] opened 2019-08-06 02:16 UTC
I use the Membership Pivot Report to report totals of various membership statues against a Custom Field on my contact.  I noticed the totals were larger in the Pivot Report than what I made them using my previous method, and it appears the cause is because I have a number of merged contacts which were being counted.

I believe a fix may be to add Contact "is_deleted" as a filter option, and am about to submit a pull request that does this.  Although I'm not fully sure whether this will have any other consequences.

**Comment by francescbassas** [comment] 2020-07-15 10:08
We just ran into this bug. @am2605 Do you have any PR that can be applied?

**Comment by am2605** [comment] 2020-07-15 11:14
The PR I submitted never got merged because it caused some tests to fail.  I didn’t understand why so I wasn’t able to progress it any further - hopefully one of the project leads might be able to work it out

**Comment by francescbassas** [comment] 2020-07-15 11:27
@am2605 https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/296 works for you?

**Comment by am2605** [comment] 2020-07-15 12:36
> @am2605 #296 works for you?

I haven’t really looked I’m sorry, so I can’t confirm

**Comment by eileenmcnaughton** [comment] 2020-11-20 23:01
I just merged a fix on this one

**Comment by francescbassas** [comment] 2021-09-06 08:43
It seems that https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/296 not solves this issue. I just reproduced with the 5.10 extension's version.

**Comment by eileenmcnaughton** [comment] 2021-09-06 08:55
@francescbassas a lot of this stuff can done using search kit now

**Comment by francescbassas** [comment] 2021-09-06 09:50
@eileenmcnaughton a membership report crossing membership type and membership statuses?

In any case I could propose and test something based on https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/296.

**Comment by eileenmcnaughton** [comment] 2022-01-05 21:30
@francescbassas did you want to put up a patch for this still?

**Comment by francescbassas** [comment] 2022-01-07 16:18
@eileenmcnaughton I have noticed that the problem is no longer valid. Since #296 you can set value for the filter "is deleted".

However, I think it would be of great help and would resemble the behavior of the core reports, if by default all reports had the values of "is deleted" and "is deceased" set to false.

I checked locally to set this default filters [here](https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/blob/master/CRM/Extendedreport/Form/Report/ExtendedReport.php#L3058) and worked. I have doubts that it is the right place. Especially with regard to the "is deceased" filter.

**Comment by eileenmcnaughton** [comment] 2022-01-07 21:01
@francescbassas I guess it should be set in getContactColumns - the gotcha is that if the filter is set it means the contact table will be joined in (usually a good thing but I think there are some edge cases - eg. when it is joined in via another table & has the then effect of inner joining in that table)

**Comment by francescbassas** [comment] 2022-01-07 21:38
@eileenmcnaughton but I don't see any reason why someone by default would want include to search deceased or deleted contacts. And if it is being done I am sure that in most cases it must be due to ignorance and causing unwanted results (as was my case).

**Comment by eileenmcnaughton** [comment] 2022-01-07 22:24
@francescbassas I think it's safer passed into the `getColumns` function - otherwise you risk say it adding the soft credit contact with those filters - and then excluding rows with no soft credti contact

**Comment by francescbassas** [comment] 2022-01-14 11:28
Thanks @eileenmcnaughton. I really hadn't thought about all the casuistry. Seeing it like this, I would only think of leaving the "is deleted" filter to "no" by default. Set "is deceased" filter to "no" could backfire in many cases. For example in the case of a donation summary.

In any case, I think this ticket can be closed. And if you consider it appropriate, another could be opened to finish maturing setting "is deleted" filter to no by default.

**Comment by eileenmcnaughton** [comment] 2022-01-14 19:06
@francescbassas just noting that I don't think there is much that extended reports does that can't be done by search kit now

**Comment by francescbassas** [comment] 2022-01-18 18:33
@eileenmcnaughton pivot tables are out of scope of Search Kit (at least for now) https://chat.civicrm.org/civicrm/pl/eg1mjf33abdefd955jzcmxhrdc

**Comment by eileenmcnaughton** [comment] 2022-01-18 20:34
Oh yeah I guess that's true

**Comment by eileenmcnaughton** [comment] 2022-05-25 23:54
well since this discussion Pivot tables have been added to search kit - targetting 5.51

**Closed** 2022-10-29 07:46 UTC
Labels: wontfix

**Comment by francescbassas** [comment] 2024-03-13 18:28
See https://chat.civicrm.org/civicrm/pl/ta6or5o63383uqhzgs5a4dsxka
