### ISSUE TITLE
Fatal Error On Wordpress After Upgrade to CiviCRM 5.52.0

### ISSUE THREAD

**Issue by themak1985** [eileenmcnaughton/nz.co.fuzion.extendedreport#516] opened 2022-08-05 04:02 UTC
Upgraded to CiviCRM 5.52.0 on WordPress and extended reports causes a fatal error.

Fatal error: Access level to CRM_Extendedreport_Form_Report_ExtendedReport::$_from must be public (as in class CRM_Report_Form) in /home/prinyc/www/www/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php on line 11

I did not get a wordpress fatal error, but I did get a HTTP ERROR 500 when accessing any extended report after i installed the extension on the civicrm wordpress demo.
https://wpmaster.demo.civicrm.org/

**Comment by eileenmcnaughton** [comment] 2022-08-05 04:22
I think this is fixed in github -  I did tag a release yesterday (5.15) but I put civi compat to 5.52 & that wasn't out when I posted  and got an email...

This is a message from the automated release system on civicrm.org.
Congratulations on releasing version 5.15 of extension 'Extended Reports'.

Unfortunately we have found a few errors while processing your release:
- The Version Compatibility tag contains an incorrect value.

You will need to correct these errors before we can accept this release.

Further help is available in the developer guide at
https://docs.civicrm.org/dev/en/latest/extensions/publish/.

You can also request help on Mattermost at
https://chat.civicrm.org/civicrm/channels/extensions.

If you no longer wish to publish this release, deleting the 5.15 tag from
your extension's repository will stop these notices.

Thank you so much for being an active contributor to CiviCRM and our
community.

**Comment by themak1985** [comment] 2022-08-05 04:36
Just tested, 5.15 fixes the problem - closing this issue. 
Thanks @eileenmcnaughton

**Comment by kcristiano** [comment] 2022-08-07 14:11
Thanks @eileenmcnaughton 

I see you tagged this release 5.52  That means we'll need to manually update to 5.15 before upgrading to CiviCRM 5.52.x   Could we target 5.51 in info.xml instead?  It would make the upgrade process a bit easier for most.

**Comment by eileenmcnaughton** [comment] 2022-08-07 21:13
@kcristiano I'm fine with that - it would need an extra release. Generally I just tag whatever version I test it on

**Comment by kcristiano** [comment] 2022-08-08 11:42
Thanks Eileen

**Comment by themak1985** [comment] 2022-08-09 14:46
@eileenmcnaughton @kcristiano 5.16 seems like a lot more that just an info.xml target change - upgraded to 5.16 from 5.15 and received another fatal error. Also was able to replicate when accessing a report on a clean install of extended reports on the demo master for wordpress civicrm.

**Comment by kcristiano** [comment] 2022-08-09 15:28
So on new buildkit installs I can reproduce - on the production sites I've upgraded I am OK so far....

```
[09-Aug-2022 11:24:46 America/New_York] PHP Fatal error:  Declaration of CRM_Extendedreport_Form_Report_Contribute_BookkeepingExtended::fromClauses() must be compatible with CRM_Extendedreport_Form_Report_ExtendedReport::fromClauses(): array in /srv/www/buildkit/wpclean/web/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/Contribute/BookkeepingExtended.php on line 202
[09-Aug-2022 11:25:35 America/New_York] PHP Fatal error:  Uncaught TypeError: Return value of CRM_Extendedreport_Form_Report_ExtendedReport::getInstanceID() must be of the type int, null returned in /srv/www/buildkit/wpclean/web/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php:389
Stack trace:
#0 /srv/www/buildkit/wpclean/web/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/extendedreport.php(111): CRM_Extendedreport_Form_Report_ExtendedReport->getInstanceID()
#1 /srv/www/buildkit/wpclean/web/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(275): extendedreport_civicrm_preProcess()
#2 /srv/www/buildkit/wpclean/web/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(136): CRM_Utils_Hook->runHooks()
#3 /srv/www/buildkit/wpclean/web/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(252): CRM_Utils_Hook_WordPress->invokeViaUF()
#4 /srv/www/buildkit/wpclean/web/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Civi\Core\Civi in /srv/www/buildkit/wpclean/web/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php on line 389
```

php 7.4   
tested CiviCRM 5.51, 5.52, and master

**Comment by kcristiano** [comment] 2022-08-09 15:37
For me https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/commit/00ff02a54337309c3531fa7fd4c6768744fd94bf  is causing the issue - If I use v 5.15 I am OK.  5.16 also has this commit in and that seems to be the issue.   Sorry I missed that when I tested.

**Comment by andyburnsco** [comment] 2022-08-09 17:13
On Civi 5.51.1 I do not get a backtrace, just WSOD with 5.16. Occurs on `CRM_Extendedreport_Form_Report_Contribute_Contributions`. Went to 5.15.

**Comment by eileenmcnaughton** [comment] 2022-08-09 22:35
The issue is around PHP getting stricter & hence to support php 8 core is declaring various things more strictly - eg. function visibility & return types. If the functions in extended reports extend core & don't have at least as strict return hints / visibily then we get errors - I put up a PR that changes a whole lot to be stricter - https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/518 - if that passes I will merge

**Comment by eileenmcnaughton** [comment] 2022-08-11 19:36
Tests are passing now - I did a big cleanup so there could still be issues in master - I pushed through & fixed most type hints, return hints & visibilities in the hope of getting ahead of this after all this whack-a-mole - however, since it is actively failing now the updated version must be better so I will tag...

**Comment by kcristiano** [comment] 2022-08-13 14:04
@eileenmcnaughton I've applied 5.17 to two sites so far and both fatal.

WP 5.9 on one site, WP 6.0 on another. WP 5.9 is on php 7.4, WP 6.0 is on php 8.0.  Tested on CiviCRM 5.52 and master

  Errors are when crating reports from template  `/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Freport%2Ftemplate%2Flist&reset=1`  Any extended report template fails.  Oddly existing reports sometimes work.  I cannot figure out a pattern.

If you need more logs I'll post beut here is one 

```
[13-Aug-2022 09:54:26 America/New_York] PHP Fatal error:  Uncaught TypeError: CRM_Extendedreport_Form_Report_ExtendedReport::getInstanceID(): Return value must be of type int, null returned in /home/cvexttest/public_html/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php:389
Stack trace:
#0 /home/cvexttest/public_html/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/extendedreport.php(111): CRM_Extendedreport_Form_Report_ExtendedReport->getInstanceID()
#1 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(275): extendedreport_civicrm_preProcess('CRM_Extendedrep...', Object(CRM_Extendedreport_Form_Report_Event_EventOverview))
#2 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(136): CRM_Utils_Hook->runHooks(Array, 'civicrm_preProc...', 2, 'CRM_Extendedrep...', Object(CRM_Extendedreport_Form_Report_Event_EventOverview), NULL, NULL, NULL, NULL)
#3 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(252): CRM_Utils_Hook_WordPress->invokeViaUF(2, 'CRM_Extendedrep...', Object(CRM_Extendedreport_Form_Report_Event_EventOverview), NULL, NULL, NULL, NULL, 'civicrm_preProc...')
#4 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), 'hook_civicrm_pr...', Object(Civi\Core\CiviEventDispatcher))
#5 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'hook_civicrm_pr...', Object(Civi\Core\Event\GenericHookEvent))
#6 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'hook_civicrm_pr...', Object(Civi\Core\Event\GenericHookEvent))
#7 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(209): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Civi\Core\Event\GenericHookEvent), Object(Civi\Core\Event\GenericHookEvent))
#8 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(167): Civi\Core\CiviEventDispatcher->dispatch('hook_civicrm_pr...', Object(Civi\Core\Event\GenericHookEvent))
#9 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(453): CRM_Utils_Hook->invoke(Array, 'CRM_Extendedrep...', Object(CRM_Extendedreport_Form_Report_Event_EventOverview), NULL, NULL, NULL, NULL, 'civicrm_preProc...')
#10 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(670): CRM_Utils_Hook::preProcess('CRM_Extendedrep...', Object(CRM_Extendedreport_Form_Report_Event_EventOverview))
#11 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php(76): CRM_Core_Form->buildForm()
#12 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Extendedreport_Form_Report_Event_EventOverview), 'display')
#13 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Extendedreport_Form_Report_Event_EventOverview), 'display')
#14 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle('display')
#15 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run()
#16 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Report/Page/Report.php(56): CRM_Utils_Wrapper->run('CRM_Extendedrep...', NULL, Array)
#17 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(319): CRM_Report_Page_Report->run(Array, NULL)
#18 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem(Array)#19 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke(Array)#20 /home/cvexttest/public_html/wp-content/plugins/civicrm/civicrm.php(1199): CRM_Core_Invoke::invoke(Array)
#21 /home/cvexttest/public_html/wp-includes/class-wp-hook.php(307): CiviCRM_For_WordPress->invoke('')
#22 /home/cvexttest/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#23 /home/cvexttest/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#24 /home/cvexttest/public_html/wp-admin/admin.php(259): do_action('toplevel_page_C...')
#25 {main}
  thrown in /home/cvexttest/public_html/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php on line 389
```

On a D7 buildkit of master I get:

```
TypeError: Return value of CRM_Extendedreport_Form_Report_ExtendedReport::getInstanceID() must be of the type int, null returned in CRM_Extendedreport_Form_Report_ExtendedReport->getInstanceID() (line 371 of /srv/www/buildkit/d7cv/web/sites/default/files/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).
```

**Comment by mwestergaard** [comment] 2022-08-13 16:55
Same here on my dev platform. Wordpress 6.0.1, CiviCRM 5.52.2, PHP 7.4, MariaDB 15.1 on Raspberry Pi (don't laugh!). Existing reports seem fine.

**Comment by eileenmcnaughton** [comment] 2022-08-14 22:19
OK - I've fixed the type hint there - will do another drop

**Comment by kcristiano** [comment] 2022-08-15 11:07
Thanks.  5.18 is working on both php 7.4 and php 8.0 for me now.

**Comment by mwestergaard** [comment] 2022-08-15 13:17
Good here, too. Thanks!

**Comment by eileenmcnaughton** [comment] 2022-08-15 19:31
yay

**Closed by eileenmcnaughton** 2022-08-15 19:31 UTC
