### ISSUE TITLE
Custom date ranges and line total filters don't "stick"

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#32] opened 2015-06-09 23:01 UTC
We do most of our financial reporting based on a fiscal year, which for us starts on October 1st.  So none of the preset date options for Receive Date are appropriate.  We have gotten used to setting a custom date range for each report.  There is an issue with price/lineitem reports though.

However in common reports which we want to run over and over again, we save the report with the filters set.  This works for the first time you run the report.  If you want to tweak the settings though... say, change which line item financial types are included, it has "forgotten" the date range and you must reset it again.  Same is true with line total filters.

Steps to replicate:
Select a price/lineitem report
Set the Receive Date filter to be from Oct 1 2014 to (empty) or whatever.
Preview the report, and note that it is correctly searching on the date set above
Add a filter to line item financial types
Preview the report, and note that it has "forgotten" the date filter.

Steps to properly save a date filter:
Select a price/lineitem report
Set the Receive Date filter to be from Oct 1 2014 to (empty) or whatever.
Update the report, or create a copy.  DO NOT preview, export, PDF or whatever because after you do that, it will have forgotten the date filter.

So, it can save the filter to the report defaults.  The fault is likely when the default values are reloaded to the UI after previewing.

**Comment by robbrandt** [comment] 2015-08-17 22:12
Have you been able to confirm this bug?  We have to deal with in on just about every report we use, unfortunately.

**Comment by joannechester** [comment] 2015-08-24 02:10
I am seeing this on one of our 6 reports that are based on the price/lineitemdatetime template.  The other 5 are operating correctly.

**Comment by eileenmcnaughton** [comment] 2016-05-10 05:04
I just tried this now (on 4.7) & it didn't forget the defaults. Is this still current? Oddly enough it's possible to filter by 'Next fiscal year' but not 'This fiscal year' - those criteria are coming from core though. You can configure your fiscal year into CiviCRM - although I can't recall where off the top of my head

**Comment by eileenmcnaughton** [comment] 2017-01-01 08:50
closing since I believe this was fixed a while ago & just not confirmed

**Closed by eileenmcnaughton** 2017-01-01 08:50 UTC
