### ISSUE TITLE
Bookkeeping Extended Report -- Doubling/Tripling/Quadrupling results with multi-membership pricesets

### ISSUE THREAD

**Issue by litespeedmarc** [eileenmcnaughton/nz.co.fuzion.extendedreport#76] opened 2016-12-02 06:39 UTC
Create a price set that has memberships for 2 or more orgs, each org with different financial types & accounts.
E.g., Org1 + JournalOrg

Use that price set (pick both orgs).

*Expected Results*
Reporting on all bookkeeping extended entries will show 2 financial types being used

*Actual Results*
Reporting on all bookkeeping extended entries will shows 4 financial types being used

**Comment by litespeedmarc** [comment] 2016-12-02 06:42
The reason for this, which may possibly have been the cause to issue #48, is the way we join {{Payment}} and {{lineItem}}.  If {{lineItem}} is for a membership, then we should only be joining {{Payment}} on that membership type.

I have a patch ready (but can't commit right now... got to go very soon), but essentially, moves the civicrm_payment join, down like so:

```
              LEFT JOIN civicrm_line_item line_item
                    ON  fitem.entity_id = line_item.id AND fitem.entity_table = 'civicrm_line_item'
                    
		    LEFT JOIN civicrm_membership_payment payment
                    ON ( contribution.id = payment.contribution_id 
                    		AND (line_item.price_field_value_id IS NULL
                    					OR EXISTS(SELECT 1
                    					            FROM civicrm_membership m2
                    					           WHERE m2.id = payment.membership_id
                    					             AND m2.membership_type_id = (SELECT membership_type_id
                    					             							FROM civicrm_price_field_value pfv
                    					             						    WHERE pfv.id = line_item.price_field_value_id)
                    					             						 )
									   )
	                  )
```

**Comment by eileenmcnaughton** [comment] 2016-12-02 08:50
In theory from 4.5 or 4.6 on the entity_id/ entity_table combo via the line item table should make the membership_payment table redundant.

It does seem, however, that there may be some data inconsistencies on some sites that make this less than 100% reliable

**Comment by litespeedmarc** [comment] 2016-12-02 21:08
So you're saying then potentially getting rid of {{civicrm_membership_payment}} altogether, and join on the line_item instead?

Something like this?
```  left join civicrm_line_item mem_line_item on mem_line_item.price_field_id = line_item.price_field_id and mem_line_item.contribution_id = contribution.id and mem_line_item.entity_Table = 'civicrm_membership'
  LEFT JOIN civicrm_membership membership ON membership.id = mem_line_item.entity_id
```

I think that's dependant on the quickconfig stuff working, which I'm not sure it always is -- though where I am at, it's all working fine.

Either way, it sounds cleaner, and it also produces two rows as I'd expect.  Any preference?  I'll push whatever is more likely to get through :)

**Comment by eileenmcnaughton** [comment] 2016-12-05 03:44
Let's go for line item. In theory it should be equally correct. In practice there have been some bugs around the data - but I think it would be better to flush them out than to ignore them

**Comment by eileenmcnaughton** [comment] 2017-01-06 05:35
I tested this out and found that if I purchase 2 line items from 2 different organisations using a price set (back office) the wrong line items are created. I get 3 line items instead of 2. The erroneous one relates the the default membership price set.

So this is a core bug (affects 4.7.15) not a bug in this extension

**Comment by litespeedmarc** [comment] 2017-01-07 22:04
Hi Eileen,

I'm just re-ramping up on this stuff.  It's been a while now, but I'm confident that that in 4.7.12, there was nothing wrong with the line-items, and even more confident of the change required to the reporting extension.

Going from memory & the comments above here, the error relates to the join on civicrm_membership_payment.  The join (prior to my PR) assumes that there is only one membership per contribution, which is erroneous.  There should be a further join to ensure that, when using price sets, we join civicrm_membership_payment relevant to the line-item.  

The end-result was the first complicated join clause that I wrote in my first comment from Dec 2nd, above.  Your comment / suggestion that civicrm_membership_payment shouldn't be required (we can use the line-item), allowed to simplify the join to the one specified on my second comment from Dec. 2nd.

For example, from our production system, we have a member that used a price set to renew for 4 memberships at once.  The end_result in terms of this query:

```
select c.contact_id,
       c.id,
       li.entity_table,
       li.price_field_id,
       memtype.member_of_contact_id
  from civicrm_contribution c 
  		left join civicrm_line_item li on li.contribution_id = c.id
  		left join civicrm_price_field_value pfv on pfv.id = li.price_field_value_id
  		left join civicrm_membership_type memtype on memtype.id = pfv.membership_type_id
  		--left join civicrm_membership_payment payment on payment.contribution_id = c.id
 where contact_id = 84861
```

Is the following

```
84861	1000038	civicrm_membership	499	7
84861	1000038	civicrm_membership	500	5
84861	1000038	civicrm_membership	500	6
84861	1000038	civicrm_membership	501	8
84861	1000038	civicrm_contribution	505	
84861	1000038	civicrm_contribution	510	
```

If I uncomment the left join, which brings the SQL closer to what was previously in the report extension, then I get 24 rows, and all amounts multiplied by 4.

**Comment by eileenmcnaughton** [comment] 2017-01-08 20:10
Hmm - maybe there was a regression in 4.7.14. If you are on the dev list you will have seen the requests to people to test that release due to complicated changes to test a critical bug. 

I think the join we are talking about is this one:
```
  function joinMembershipFromContribution() {
    $this->_from .= "
LEFT JOIN civicrm_membership_payment pp
ON {$this->_aliases['civicrm_contribution']}.id = pp.contribution_id
LEFT JOIN civicrm_membership {$this->_aliases['civicrm_membership']}
ON pp.membership_id = {$this->_aliases['civicrm_membership']}.id";
  }
```
I've just switched it to join off the line item. Re our earlier conversation on whether some sites may not have the correct linkages in the line item table to the civicrm_membership record. I think on reflection a reporting extension is not the place to compensate for that.

**Comment by litespeedmarc** [comment] 2017-01-08 23:53
Sounds right, though the place I had changed was in
BookeepingExtended.from(), so you may have to fix it in two spots (or
refactor the one).  Good thing about the from(), is that it was real easy
to read & follow!

```
              -- to get the membership
              LEFT  JOIN civicrm_line_item $line_item
                      ON fitem.entity_id = $line_item.id AND
fitem.entity_table = 'civicrm_line_item'
              LEFT  JOIN civicrm_line_item mem_line_item
                      ON mem_line_item.price_field_id =
$line_item.price_field_id
                     AND mem_line_item.contribution_id = contribution.id
                     AND mem_line_item.entity_Table = 'civicrm_membership'

              -- Next join just in case contribution does not have a price
set associated to it.
              -- Typically, anything with a membership *would* get a price
set (either user configured
              -- or a quick config one).  But for historical or unconfirmed
'hear-say' bugs reasons,
              -- this may or may not.  Keeping this historical 'more
dangerous join' just in case.
              LEFT  JOIN civicrm_membership_payment payment
                      ON $contribution.id = payment.contribution_id
                  AND $line_item.price_field_id IS NULL -- IS NULL because
if there is a price set
                                                        -- Then this join
shouldn't be used.

              -- The membership join.  Ideally, just on mem_line_item, but
for 'just-in-case' reasons,
              -- Also keep legacy join on payment.membership_id, if
mem_line_item join fails.
              LEFT  JOIN civicrm_membership $membership
                      ON $membership.id = COALESCE(mem_line_item.entity_id,
payment.membership_id)
                      ```

Of course if you leave out civicrm_membership_payment (sounds like a good
change to me), then the SQL would be simplified.

**Comment by eileenmcnaughton** [comment] 2017-01-09 00:55
Do you want to test the latest version from github & see how it goes.

Also, you should probably test the next 4.7 rc to check if the line items are being created correctly under your scenario & log a ticket if not. Someone may or may not pick it up & fix it but it's more likely they will if a JIRA exists

**Comment by eileenmcnaughton** [comment] 2017-02-06 11:23
I'm going to close this because I think it is fixed but please re-open if not

**Closed by eileenmcnaughton** 2017-02-06 11:23 UTC
